### PR TITLE
Detect uppercase date time formats

### PR DESCRIPTION
**Pull request by zeehio**
Hi,

The `dates-1900.xls` once opened and saved using LibreOffice 5 was not readable by `readxl` (it detected dates as numbers).

This patch allows to detect uppercase date time formats (used at least by libreoffice). A test case is included. Note that the test fails due to [different autogenerated col_names in xls and xlsx](https://github.com/hadley/readxl/pull/98)

EDIT: Excel is able to parse the file so I assumed that readxl should be capable too, otherwise the pull request would have gone to libreoffice.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Note that this closes #134.

@zeehio I guess it's best to amend the commit message so the issue closing happens automatically?

**Comment by zeehio** [comment]
I updated the commit message. Please note that readxl  has been like this for 8 months, so the chances of this being merged in the next few days are not huge. Hopefully eventually someone will work a bit on the package and will deal with the increasing number of pull requests.

(I am just another random readxl user, there is not much more I can do)

**Comment by MichaelChirico** [comment]
I hear you, there are a couple of good PRs that would improve the package a lot but it appears it's been on the shelf for some time

**Comment by jennybc** [comment]
@MichaelChirico readxl and these PRs will get handled in early 2017

**Comment by hadley** [comment]
Looks good. Can you please add a bullet to NEWS.md?

**Comment by zeehio** [comment]
Rebased on master and done

**Pull request merged**
