### PR TITLE
NA strings count as empty column names when determining empty columns

### PR DESCRIPTION
**Pull request by jmarshallnz**
My bad :)  I'll update the test sheets after the long weekend to make sure we correctly drop columns as well if you want to hold off merging until then.

### CODE REVIEW

**Comment by hadley** [comment]
It's not a long weekend here :(

**Comment by hadley** [comment]
Would you mind merging/rebasing too please?

**Comment by jmarshallnz** [comment]
Sure :)

**Comment by hadley** [comment]
Perfect - thanks! I'm going to submit to CRAN v. shortly

**Pull request merged**
