### PR TITLE
add repo for cyclic dep check, add notifications

### PR DESCRIPTION
**Pull request by bquast**

### CODE REVIEW

**Comment by hadley** [comment]
Do you need those notifications? I think they're just the defaults.

**Comment by bquast** [comment]
I suppose not, I added them because they are in the devtools template, I believe Craig Citro put them there. The repo is helpful though, having no notes is nice and clean

**Comment by bquast** [comment]
I've also created a pull request with the repo added in the devtools template

**Comment by bquast** [comment]
I've removed the notification lines from request

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
